server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.189.50:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    initialize: false
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 39.105.189.50
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true