server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 39.105.189.50
#阿里云accessKey配置
aliyun:
  sms:
    accessKeyId: LTAIYK2J0kK1HzVS
    accessKeySecret: fGbTXM9R4uVgt8g2Cr97wF9NypmHEM
    sign_name: Bingo之家
    template_code: SMS_155855084
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true